fix: Fix status codes and corresponding schemes
BulbProject/bulb-project-api pull request #68
Opened 2020-08-27 13:40 UTC by natalia-lypovyk

2020-08-27 13:53 UTC, semenov-ol approved these changes

2020-08-28 08:14 UTC, drizzer14 requested changes

2020-08-28 08:14 UTC, drizzer14 commented on src/do/entity/requirement-response/requirement-response.entity.ts
> +    oneOf: [{ type: 'string' }, { type: 'number' }, { type: 'boolean' }],
`integer` здесь вроде бы тоже нужен, если не ошибаюсь.

2020-08-28 08:14 UTC, drizzer14 commented on src/do/entity/variant/observation.entity.ts
> +    oneOf: [{ type: 'string' }, { type: 'number' }],
`integer`

2020-08-28 09:41 UTC, mrrotberry requested changes
Присутствуют неточности в документации, поле `value` не описано в модели тела запроса

2020-08-31 10:33 UTC, drizzer14 approved these changes

2020-09-01 11:32 UTC, drizzer14 requested changes

2020-09-01 11:32 UTC, drizzer14 commented on src/do/algorithms/algorithms.service.ts
> +  public readonly algorithms: Record<string, AlgorithmEngine> = {
Для чего?

2020-09-01 11:32 UTC, drizzer14 commented on src/do/algorithms/algorithms.module.ts
> +import { VersionsPackageRepositoryModule } from '../../shared/repositories/versions-package';
Структуру импортов соблюдай, пожалуйста.

2020-09-01 11:32 UTC, drizzer14 commented on src/do/algorithms/services/calculation/calculation.service.ts
> +      throw new InternalServerErrorException(`Algorithm for category ${categoryId} do not exist.`);
`does not`

2020-09-01 11:32 UTC, drizzer14 commented on src/do/algorithms/services/calculation/calculation.service.ts
> +      throw new BadRequestException(`Calculation is impossible for archive version.`);
`archived`

2020-09-01 11:32 UTC, drizzer14 commented on src/shared/utils/get-last-version-number.ts
> +export const getLastVersionNumber = (versions: string[]): string => {
А нельзя тут сразу вернуть `number`?

2020-09-01 11:32 UTC, drizzer14 commented on src/manage/guards/id-conformance.guard.ts
> +    const bodyId = context.switchToHttp().getRequest().body?.id;
Здесь пустого `body` быть не должно.

2020-09-01 11:32 UTC, drizzer14 commented on src/shared/repositories/category-version/category-version-repository.service.ts
> +import { getLastVersionNumber } from '../../utils/get-last-version-number';
Экспорт из индекса сделай, пожалуйста, по аналогии со всеми утилитами во всех проектах, которые мы делаем.

2020-09-01 11:40 UTC, semenov-ol commented on src/do/algorithms/algorithms.service.ts
> +  public readonly algorithms: Record<string, AlgorithmEngine> = {
для проверки переданной категории с доступными алгоритмами в `calculation.service`

2020-09-01 11:45 UTC, semenov-ol commented on src/manage/guards/id-conformance.guard.ts
> +    const bodyId = context.switchToHttp().getRequest().body?.id;
Сталкивались с ошибкой, что здесь `body` undefined

2020-09-01 12:17 UTC, mrrotberry commented on src/do/algorithms/algorithms.module.ts
>  import { CategoryVersionRepositoryModule } from '../../shared/repositories/category-version';
Абсолютные импорты, пожалуйста

2020-09-01 12:43 UTC, drizzer14 commented on src/manage/guards/id-conformance.guard.ts
> +    const bodyId = context.switchToHttp().getRequest().body?.id;
Этот гард отвечает за проверку соответствия `id`, а не за валидацию всего `body`.

2020-09-01 12:45 UTC, drizzer14 requested changes

2020-09-01 12:45 UTC, drizzer14 commented on src/do/algorithms/services/calculation/calculation.service.ts
> +    }
Оставь `todo` комменты в таких местах, чтобы потом мы не забыли поправить валидацию.

2020-09-01 12:45 UTC, drizzer14 commented on src/shared/repositories/category-version/category-version-repository.service.ts
> +import { formatDate, getLastVersionNumber } from '../../utils';
Кстати, вопрос, эта функция относится только к этому классу?
Если да, то пусть она будет его приватным методом.

2020-09-01 13:01 UTC, semenov-ol commented on src/shared/repositories/category-version/category-version-repository.service.ts
> +import { formatDate, getLastVersionNumber } from '../../utils';
она еще используется в одном классе

2020-09-01 13:55 UTC, mrrotberry approved these changes

2020-09-01 14:46 UTC, merged