feat: Add features for motors calculation
BulbProject/bulb-project-api pull request #70
Opened 2020-08-31 16:30 UTC by mrrotberry

2020-09-03 14:04 UTC, semenov-ol approved these changes

2020-09-04 09:29 UTC, drizzer14 requested changes

2020-09-04 09:29 UTC, drizzer14 commented on src/do/entity/algorithm-engine.ts
> +  public getModeOfUse(requirementResponses: RequirementResponse[], criterionNumber: string): ModeOfUse | void {
Не хочешь добавить к названиям этих методов приставку `try`? Всё-таки, читая `getModeOfUse`, я ожидаю в любом случае получить `modeOfUse`, а могу получить нихера.

2020-09-04 09:29 UTC, drizzer14 commented on src/do/algorithms/categories/31110000-0.ts
> +      const normalizeRequestedPower = /-/.test(requestedPower)
`normalized`

2020-09-04 10:07 UTC, drizzer14 approved these changes

2020-09-04 10:45 UTC, merged