feat: Add conformance.service, Add guard for not existed category
BulbProject/bulb-project-api pull request #72
Opened 2020-09-04 09:21 UTC by semenov-ol

2020-09-04 09:32 UTC, drizzer14 commented on src/do/algorithms/services/specification/specification.service.ts
> +      throw new BadRequestException(`Requested body is empty`);
Может всё-таки `request body`?

2020-09-04 09:33 UTC, drizzer14 commented on src/do/do.controller.ts
> +import { ExistedAlgorithmGuard } from './guards/existed-algorithm.guard';
- [ ] Экспорт из индекса
- [ ] Грамотное название

2020-09-04 09:36 UTC, mrrotberry requested changes

2020-09-04 09:36 UTC, mrrotberry commented on src/do/algorithms/services/specification/specification.service.ts
> +      throw new BadRequestException(`Requested body is empty`);
Это просто констатация, давай укажем клиенту именно на то что так быть не должно и не забудь точку в конце)

2020-09-04 09:36 UTC, mrrotberry commented on src/do/do.controller.ts
>        oneOf: [
oneOf тут не нужен, ты же возвращаешь при этом коде только JSON

2020-09-04 09:36 UTC, mrrotberry commented on src/do/guards/existed-algorithm.guard.ts
> +    return true;
Добавь пожалуйста пустую строку перед возвратом

2020-09-04 09:36 UTC, mrrotberry commented on src/do/services/conformance/conformance.service.ts
> +    if (categoryVersion.status === 'pending') {
Тут надежней сделать проверку на то что категория НЕ в статусе `active`, о чем и сказать в ошибке

2020-09-04 09:37 UTC, drizzer14 commented on src/do/guards/existed-algorithm.guard.ts
> +}
Мы разве не решили отдать это под ответственность сервиса алгоритмов?

2020-09-04 09:38 UTC, drizzer14 commented on src/do/services/conformance/conformance.service.ts
> +      throw new BadRequestException('Calculation is impossible because category status is pending.');
Я бы написал `Calculation is impossible for pending category`

2020-09-04 09:38 UTC, drizzer14 commented on src/do/services/conformance/conformance.service.ts
> +      throw new BadRequestException('Calculation is impossible because category status is pending.');
Или даже `Calculation is only possible for active category`

2020-09-04 09:39 UTC, drizzer14 commented on src/do/services/docx-generator/docx-generator.service.ts
> +              currentItem.classification.id as string
`as string` здесь точно надо?

2020-09-04 10:36 UTC, semenov-ol commented on src/do/do.controller.ts
> +import { ExistedAlgorithmGuard } from './guards/existed-algorithm.guard';
подскажи пример названия, пожалуйста

2020-09-04 12:53 UTC, drizzer14 requested changes

2020-09-04 12:53 UTC, drizzer14 commented on src/do/algorithms/algorithms.module.ts
> +import { DocumentsService, DocxGeneratorService, CsvService } from '../services';
Не, всё равно неправильно.
Вспоминай порядок импортов.

2020-09-04 12:53 UTC, drizzer14 commented on src/do/algorithms/services/specification/specification.service.ts
> +      throw new BadRequestException(`Field 'relatedItem' is not match.`);
`does not`

2020-09-07 10:19 UTC, mrrotberry approved these changes

2020-09-07 10:30 UTC, drizzer14 requested changes

2020-09-07 10:30 UTC, drizzer14 commented on src/do/algorithms/algorithms.module.ts
> +import { SpecificationService, CalculationService } from './services';
Пустую строку.

2020-09-08 14:59 UTC, drizzer14 requested changes

2020-09-08 14:59 UTC, drizzer14 commented on src/do/algorithms/algorithms.module.ts
>  import { DocumentsService, DocxGeneratorService, CsvService } from '../services';
Не там ты пустую строку добавил. Смотри на форматирование импортов и делай сразу нормально, пожалуйста. Это не сложно, надо просто выработать привычку.

2020-09-09 11:15 UTC, drizzer14 approved these changes

2020-09-09 13:02 UTC, merged