refactor: Refactoring categories.controller
BulbProject/bulb-project-api pull request #73
Opened 2020-09-04 13:52 UTC by semenov-ol

2020-09-07 10:23 UTC, mrrotberry approved these changes

2020-09-07 10:30 UTC, drizzer14 requested changes

2020-09-07 10:30 UTC, drizzer14 commented on src/categories/categories.controller.ts
> +import { HttpExceptionFilter } from '../shared/filters';
👆

2020-09-07 10:30 UTC, drizzer14 commented on src/categories/categories.controller.ts
> +  public async getListEntries(@Query() query: QueryDto): Promise<CategoriesListEntry[] | CategoryDetails[]> {
Это работает из без описания `query` как объекта. Любой параметр, декорированный `@Query`, принадлежит этому объекту.

2020-09-07 10:30 UTC, drizzer14 commented on src/shared/entity/category/conversion.entity.ts
> +  })
Почему валидатор убрал?

2020-09-07 10:30 UTC, drizzer14 commented on src/shared/repositories/versions-package/models/versions-package.model.ts
> +  @ApiHideProperty()
Эта штука работает?
Потому что у меня наотрез отказывалось скрывать.

2020-09-07 11:36 UTC, semenov-ol commented on src/shared/entity/category/conversion.entity.ts
> +  })
показывало в схеме как массив из этих элементов, заменил на `@ApiProperty`

2020-09-07 11:36 UTC, semenov-ol commented on src/shared/repositories/versions-package/models/versions-package.model.ts
> +  @ApiHideProperty()
да, у меня скрывает

2020-09-07 11:36 UTC, semenov-ol commented on src/categories/categories.controller.ts
> +  public async getListEntries(@Query() query: QueryDto): Promise<CategoriesListEntry[] | CategoryDetails[]> {
тогда не будет работать валидация в `QueryDto`

2020-09-07 11:37 UTC, semenov-ol commented on src/shared/entity/category/conversion.entity.ts
> +  })
показывало в схеме как массив из этих элементов, заменил на `@ApiProperty`

2020-09-07 11:38 UTC, semenov-ol commented on src/shared/repositories/versions-package/models/versions-package.model.ts
> +  @ApiHideProperty()
да, у меня скрывает

2020-09-08 14:54 UTC, drizzer14 commented on src/shared/entity/category/conversion.entity.ts
> +  })
@semenov-ol а какое отношение валидатор имеет к схеме?

2020-09-08 14:58 UTC, drizzer14 approved these changes

2020-09-09 09:28 UTC, merged