ES-4246
BulbProject/bulb-project-api pull request #87
Opened 2020-10-07 13:12 UTC by semenov-ol

2020-10-07 14:38 UTC, mrrotberry commented on src/shared/validators/is-excluded.ts
> +        return !expectedValue;
Не забывай о пустых строках перед возвратом

2020-10-07 16:50 UTC, drizzer14 requested changes

2020-10-07 16:50 UTC, drizzer14 commented on src/do/algorithms/services/calculation/calculation.service.ts
> +      throw new BadRequestException(`Requested body must be not empty object.`);
`an empty`

2020-10-07 16:50 UTC, drizzer14 commented on src/shared/validators/is-excluded.ts
> +// eslint-disable-next-line import/no-cycle
Не, от цикла надо избавиться

2020-10-07 16:50 UTC, drizzer14 commented on src/shared/validators/is-excluded.ts
> +        return `If expectedValue exist, minValue, maxValue and optionDetails should not exist.`;
Перефразируй, пожалуйста, очень плохо звучит

2020-10-08 14:25 UTC, mrrotberry approved these changes

2020-10-08 14:28 UTC, drizzer14 requested changes

2020-10-08 14:28 UTC, drizzer14 commented on src/do/algorithms/services/calculation/calculation.service.ts
> +      throw new BadRequestException(`Requested body must be not an empty object.`);
`must not be`

2020-10-08 14:28 UTC, drizzer14 commented on src/shared/validators/is-excluded.ts
> +// eslint-disable-next-line import/no-cycle
?

2020-10-08 14:28 UTC, drizzer14 commented on src/shared/validators/is-excluded.ts
> +        return `minValue, maxValue, optionDetails and expectedValue are mutually exclusive attributes.`;
Не совсем корректно описано.
Из этой ошибки кажется, что все из указанных атрибутов взаимоисключающи.

2020-10-08 14:29 UTC, mrrotberry commented on src/shared/validators/is-excluded.ts
> +// eslint-disable-next-line import/no-cycle
Это пока оставим с комментом игнора, так как тут более глобальная проблема

2020-10-08 14:31 UTC, natalia-lypovyk approved these changes

2020-10-08 14:47 UTC, semenov-ol commented on src/shared/validators/is-excluded.ts
> +// eslint-disable-next-line import/no-cycle
не скажу, что нельзя в принципе убрать цикличность, но у меня не получилось это сделать легким путем

2020-10-08 15:38 UTC, merged